# if (process.env.RUN_WEBSSH === "1") {
    # fastify.register(require('@fastify/http-proxy'), {
    #     upstream: process.env.WEBSSH_HOST,
    #     prefix: '/console',
    #     rewritePrefix: '/',
    #     websocket: true,
    #     replyOptions: {
    #         rewriteRequestHeaders: sameOrigin,
    #     },
    #     preHandler: (req, res, next) => {

    #         const host = 'console';
    #         const username = 'odoo';
    #         const password = Buffer.from("odoo").toString('base64');
    #         if (req.url.indexOf("?") == -1) {
    #             const url = req.url + `?hostname=${host}&fontsize=10&username=${username}&password=${password}&command=`
    #             res.header['Cache-Control'] = 'no-cache, no-store, must-revalidate';
    #             res.redirect(url, 301)
    #         }
    #         else {
    #             next()
    #         }
    #     },
    # });
    # fastify.register(require('@fastify/http-proxy'), {
    #     upstream: process.env.WEBSSH_HOST,
    #     prefix: '/consolestream',
    #     rewritePrefix: '/',
    #     websocket: false,
    # });
# location /consolestream {
#     proxy_pass  

#     proxy_set_header Upgrade $http_upgrade;
#     proxy_set_header Connection "upgrade";
#     proxy_set_header Host $host;
#     proxy_set_header X-Real-IP $remote_addr;
#     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#     proxy_http_version 1.1;
#     proxy_read_timeout 86400s; # Keep WebSocket connections open longer
#     # Define custom error pages
#     error_page 502 503 504 = @fallback;
# }