    # fastify.register(require('@fastify/http-proxy'), {
    #     upstream: `http://${process.env.LOGS_HOST}:6688`,
    #     prefix: '/logs',
    #     rewritePrefix: '/',
    #     websocket: true,
    # });
    # fastify.register(require('@fastify/http-proxy'), {
    #     upstream: `http://${process.env.LOGS_HOST}:6688`,
    #     prefix: '/logs_socket_io',
    #     rewritePrefix: '/socket.io',
    #     websocket: true,
    # });