# const vncvscode = "http://novnc_vscode:6080";
# const vncrobotstandalone = "http://novnc_cobot:6080";
#     fastify.register(require('@fastify/http-proxy'), {
#         upstream: vncrobotstandalone,
#         prefix: '/cobot',
#         preHandler: (req, reply, next) => {
#             reply.redirect("/vnccobot/vnc.html?autoconnect=true&path=vnccobot?token=cobot");
#             next();
#         },
#     });
#     fastify.register(require('@fastify/http-proxy'), {
#         upstream: vncvscode,
#         prefix: '/code',
#         preHandler: (req, reply, next) => {
#             reply.redirect("/vscode/vnc.html?autoconnect=true&path=vscode?token=vscode");
#             next();
#         },
#     });
#     fastify.register(require('@fastify/http-proxy'), {
#         upstream: vncvscode,
#         prefix: '/vscode',
#         rewritePrefix: '/',
#         websocket: true,
#     });
#     fastify.register(require('@fastify/http-proxy'), {
#         upstream: vncrobotstandalone,
#         prefix: '/vnccobot',
#         rewritePrefix: '/',
#         websocket: true,
#     });