FROM postgres:16-bullseye
CMD ["postgres"]
RUN apt update && \
apt install -y postgresql-server-dev-16 python-dev build-essential git python3-pip procps sockstat


ADD config* /
ADD run.sh /run.sh
COPY init/* /docker-entrypoint-initdb.d/
RUN chown -R postgres:postgres /docker-entrypoint-initdb.d && \
    chmod a+x /docker-entrypoint-initdb.d/*.sh /run.sh
